### PR TITLE
Show post visibility indicator

### LINKED ISSUE #594: [BUG] Post visibility indicator missing in app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The post visibility indicator is missing in on moats viewed in the app. 
Post as seen in app:
E7875834-E536-4453-9B7D-25B2817159C7
Post seen on web:
955DFCB5-9983-4039-B4F7-E45407505FAE

### Expected Behavior

To see the post visibility indicator. 

### Steps To Reproduce

_No response_

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: 16.2
- Version: v1.4.5
- Build: 144
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nossipova**
Fixes #594.

The sensitive content toggle is now in the upper line to the left of the menu button and the visibility indicator is at the end of the second line.

### CODE REVIEW

File: MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift [hunk 1]
```diff
@@ -283,6 +283,21 @@ extension StatusView.ViewModel {
                 authorView.dateLabel.configure(content: PlaintextMetaContent(string: text))
             }
             .store(in: &disposeBag)
+
+        $visibility
+            .map {
+                switch $0 {
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift]: I feel like this would be better placed as a public extension so it can be shared with the compose view

File: MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift [hunk 2]
```diff
@@ -283,6 +283,21 @@ extension StatusView.ViewModel {
...
+                case .public: return Asset.Scene.Compose.earth
+                case .unlisted: return Asset.Scene.Compose.people
+                case .private: return Asset.Scene.Compose.peopleAdd
+                case .direct: return Asset.Scene.Compose.mention
+                case ._other: return Asset.Scene.Compose.more
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift]: This would be confusing since there would be 2 “…” button-looking things — maybe swap it out for a ? or something?

File: MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift (hunk 1 above)
Comment (nossipova) [reply MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift]: That was also my intention at first, but there are two different visibility enums. The status view uses `MastodonVisibility` and the compose view uses `Mastodon.Entity.Status.Visibility`. I can put this into in an extension, but it cannot be shared with the compose view unless the same enum is used in both cases.

Comment (j-f1) [reply MastodonSDK/Sources/MastodonUI/View/Content/StatusView+ViewModel.swift]: Haha right, I had forgotten about that. I think I merged them in one of my open PRs, but it hasn't been merged yet.

File: MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift [hunk 3]
```diff
@@ -159,6 +159,7 @@ public enum Asset {
       public static let peopleAdd = ImageAsset(name: "Scene/Compose/people.add")
       public static let pollFill = ImageAsset(name: "Scene/Compose/poll.fill")
       public static let poll = ImageAsset(name: "Scene/Compose/poll")
+      public static let questionmarkCircle = ImageAsset(name: "Scene/Compose/questionmark.circle")
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift:158]: As far as I can tell, all of the icons here are custom ones. I think you should be able to swap to use the built-in SF Symbol (especially since the relevant symbol has been available since iOS 13)

(I like the choice of icon though!)

File: MastodonSDK/Sources/MastodonUI/Extension/MastodonVisibility+Image.swift [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+extension MastodonVisibility {
+
+    public var image: UIImage {
+        let asset: ImageAsset
+        switch self {
+        case .public: asset = Asset.Scene.Compose.earth
+        case .unlisted: asset = Asset.Scene.Compose.people
+        case .private: asset = Asset.Scene.Compose.peopleAdd
+        case .direct: asset = Asset.Scene.Compose.mention
+        case ._other: asset = Asset.Scene.Compose.questionmarkCircle
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonUI/Extension/MastodonVisibility+Image.swift:16]:
```suggestion
        case ._other: return UIImage(systemName: "questionmark.circle")
```

File: MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift (hunk 3 above)
Comment (nossipova) [reply MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift:158]: This is also a custom one, it’s just similar to the SF Symbol. What is the general preference, to use mostly custom icons or mostly SF Symbols? One SF Symbol here would probably look inconsistent with the rest.

Comment (j-f1) [reply MastodonSDK/Sources/MastodonAsset/Generated/Assets.swift:158]: Oh nice, I didn’t notice. Very cool!

**Review by zeitschlag — APPROVED** [review]
Better late than never:

Thank you @nossipova!
