### PR TITLE
Delete authentication credentials from Keychain upon logout

### LINKED ISSUE #1181: [BUG] Unable to logout from account
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

After selecting an account, going "Logout <name>", and confirming this with a "Sign out" button, it seems to work (there is no crash), the account appears logged out (it's no longer in the selection list). But, when closing and re-launching the Mastodon app, the account is there again.

This happens regardless of the account being offline or online at the time of signing out.

Deleting the app and reinstalling it also doesn't resolve it, because all previous accounts re-appear automatically. This is odd in itself.

It means there is no way to remove an account from the Mastodon app.

### Expected Behavior

After sign-out the account disappears and never reappears until adding it back on manually.

### Steps To Reproduce

1. Start app.
2. Select an account.
3. Log-out from account.
4. Force close app.
5. Re-launch app.
6. Account is there again.

### Environment

```markdown
- Device: iPhone
- OS: 17
- Version: 2023.15
```

### PR DESCRIPTION
**Pull request by kimar**
Fixes #1181

# How to reproduce

* In the App
  * Account Settings
    * Logout
  * Kill App
  * Restart App
  * Account should not be logged in anymore

### CODE REVIEW

File: MastodonSDK/Sources/MastodonCore/AuthenticationServiceProvider.swift [hunk 1]
```diff
@@ -30,7 +30,8 @@ public class AuthenticationServiceProvider: ObservableObject {
         }
     }
     
-    func delete(authentication: MastodonAuthentication) {
+    func delete(authentication: MastodonAuthentication) throws {
+        try Self.keychain.remove(authentication.persistenceIdentifier)
```
Comment (zeitschlag) [inline MastodonSDK/Sources/MastodonCore/AuthenticationServiceProvider.swift:34]: 🤦 🥲 😆

**Review by zeitschlag — APPROVED** [review]
LGTM 💯
