### PR TITLE
Fix #902: Uploaded video get's distorted because aspect ratio is not maintained

### LINKED ISSUE #902: [BUG] Uploading any videos from within the app leads to their corruption
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The app corrupts videos of various resolutions upon upload. Example: a square-ish or vertical video will be stretched (way out of bounds) vertically, and uploading a horizontal video will stretch it horizontally.

### Expected Behavior

Videos get uploaded as they are, without unexpected corruptions.

### Steps To Reproduce

1. Tap the “new post” button in dock bar.
2. Tap the media attachment icon.
3. Select any video via “Browse...” or “Photo library” options.
4. Wait for the app to process the selected video.
5. See that it got corrupted, and even after posting the video it will still be corrupted.

### Environment

```markdown
- Device: iPhone 12
- OS: iOS 16.2
- Version: v.1.4.9
- Build: 224
```

### Anything else?

reproduction steps and bug demonstration:

https://user-images.githubusercontent.com/71202418/213844978-5ce8e772-4430-43a1-8792-d979be03a522.MOV

post with corrupted video posted from the client: https://wetdry.world/@w/109725529615639721

original file that was uploaded:

https://user-images.githubusercontent.com/71202418/213845058-66986337-67c4-43ad-8c87-42478e9aee68.mp4

### PR DESCRIPTION
**Pull request by kimar**
# Rationale

Calculates the desired transcoded video size based on the current video orientation and aspect ratio.

Currently a fixed size of either `1280x720` or `720x1280` px is being used, this leads to distorted videos if the input is not in 16:9 (or 9:16 respectively) aspect ratio.

Fixes #902.

### CODE REVIEW

**Review by Gargron — APPROVED** [review]

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift [hunk 1]
```diff
@@ -13,19 +13,20 @@ import SessionExporter
...
-                return true
-            }
-            
-            let size = track.naturalSize.applying(track.preferredTransform)
-            return abs(size.width) >= abs(size.height)
-        }()
+
+        let preferredSize = try await preferredSizeFor(
+            track: track,
+            maxLongestSide: 1280
```
Comment (zeitschlag) [inline MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:28]: What's the reason, why we set this to a maximum width of 1280?

Comment (DK1DA) [reply MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:28]: Sorry haven't noticed this comment. I assume this has been defined in the past as the maximum resolution due to the Mastodon Server putting constraints on the videos. However we're going to, soon(ish), be using the server config to configure the client depending on the current server capabilities.
