### PR TITLE
Fix voted indicator on poll missing (IOS-274)

### LINKED ISSUE #1289: [BUG] Polls don’t show choice after voting
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

Polls don’t have choice marked after voting

### Expected Behavior

To have choice marked after voting

### Steps To Reproduce

1. Vote in a poll
2. Observe choice is not marked.

### Environment

```markdown
- Device:iPhone 12 pro
- OS: iOS 17.4.1
- Version: v2024.5
- Build: 6336
```

### Anything else?

image
image

### PR DESCRIPTION
**Pull request by kimar**
# Rationale

Fixes #1289

### CODE REVIEW

File: Mastodon/Diffable/Status/StatusSection.swift [hunk 1]
```diff
@@ -144,7 +144,6 @@ extension StatusSection {
         authContext: AuthContext,
         statusView: StatusView
     ) {
-        let managedObjectContext = context.managedObjectContext
```
Comment (DK1DA) [inline Mastodon/Diffable/Status/StatusSection.swift:147]: Accidentally found this leftover.

**Review by zeitschlag — APPROVED** [review]
LGTM!
