### PR TITLE
Fix no downscaling for raw image from camera issue

### LINKED ISSUE #665: [BUG] Image downscaling and upload not working in 1.4.7 (199)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I am using an iphone SE with ios version 16.1.1 and the Mastodon store app in version 1.4.7 (199).

When I composed a toot, I took a camera picture (and later retried with an already saved image) and tried to upload.
It did not work.

The iPhone created an image in the size of ˜16 MB, the upload limit is 10 MB.

I spoke with the instance administrator and he mentioned, that Mastodon should autoatically downscale images.
(e.g. in the toot! ios app, it works).

Source toot: https://sw-development-is.social/web/@maiknog/109382046552323569
Screenshot from Mastodon app: ios app Mastodon 1 4 7

### Expected Behavior

Images should automatically downscale and be able to be used in toots.

### Steps To Reproduce

1. iPhone SE; iOS 16.1.1
2. Mastodon app 1.4.7 (199)
3. Compose a toot, take a camera picture or embed from saved images
4. Try to publish

### Environment

```markdown
- Device:iPhone SE
- OS: iOS 16.1.1
- Version: Mastodon app 1.4.7 (199)
- Build: 199
```

### Anything else?

Source toot: https://sw-development-is.social/web/@maiknog/109382046552323569
Screenshot from Mastodon app: ios app Mastodon 1 4 7

### PR DESCRIPTION
**Pull request by MainasuK**
resolve #665 

The app doesn't compress images from the camera. So the attachment may always too large to upload.

This patch compresses the photo to the server image size limit (fallback to 10 MiB limit if no limitation from the server). The image input will be handled this workflow:

1. normalized png data
2. upload when smaller then size limit
3. compress to JPEG with q=0.8 (loop=1)
4. compress to JPEG with q=0.8, size_scale=0.8 (loop > 1)

### CODE REVIEW

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift [hunk 1]
```diff
@@ -92,3 +93,57 @@ extension AttachmentViewModel {
...
+        
+        repeat {
+            guard let image = KFCrossPlatformImage(data: imageData) else {
+                throw AttachmentError.invalidAttachmentType
+            }
+
+            if imageData.kf.imageFormat == .PNG {
+                // A. png image
+                if imageData.count > maxPayloadSizeInBytes {
+                    guard let compressedJpegData = image.jpegData(compressionQuality: 0.8) else {
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:116]: Do you think it would make sense to try other formats like WebP or AVIF?

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift [hunk 2]
```diff
@@ -92,3 +93,57 @@ extension AttachmentViewModel {
...
+            } else {
+                // B. other image
+                if imageData.count > maxPayloadSizeInBytes {
+                    let targetSize = CGSize(width: image.size.width * 0.8, height: image.size.height * 0.8)
+                    let scaledImage = image.kf.resize(to: targetSize)
+                    guard let compressedJpegData = scaledImage.jpegData(compressionQuality: 0.8) else {
+                        throw AttachmentError.invalidAttachmentType
+                    }
+                    os_log("%{public}s[%{public}ld], %{public}s: compress jpeg %.2fMiB -> jpeg %.2fMiB", ((#file as NSString).lastPathComponent), #line, #function, Double(imageData.count) / 1024 / 1024, Double(compressedJpegData.count) / 1024 / 1024)
+                    imageData = compressedJpegData
```
Comment (j-f1) [inline MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:134]: I’m worried that encoding a very large image as JPEG repeatedly will result in artifacts. Would it make sense to store the uncompressed image and repeatedly downscale then compress it?

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift (hunk 1 above)
Comment (MainasuK) [reply MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:116]: That's possible if the webp format is included in `Mastodon.Entity.Instance.Configuration.MediaAttachments.supportedMIMETypes`.

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift (hunk 2 above)
Comment (MainasuK) [reply MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:134]:
```
2022-11-22 20:16:26.117589+0800 Mastodon[32609:6822189] AttachmentViewModel+Compress.swift[119], compressImage(data:sizeLimit:): compress png 192.94MiB -> jpeg 18.46MiB
2022-11-22 20:16:30.005269+0800 Mastodon[32609:6822189] AttachmentViewModel+Compress.swift[133], compressImage(data:sizeLimit:): compress jpeg 18.46MiB -> jpeg 12.87MiB
2022-11-22 20:16:32.362633+0800 Mastodon[32609:6822189] AttachmentViewModel+Compress.swift[133], compressImage(data:sizeLimit:): compress jpeg 12.87MiB -> jpeg 8.81MiB
```

The loop will not be too much. So maybe not a big difference.

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift [hunk 3]
```diff
@@ -92,3 +93,57 @@ extension AttachmentViewModel {
...
+                } else {
+                    os_log("%{public}s[%{public}ld], %{public}s: jpeg %.2fMiB", ((#file as NSString).lastPathComponent), #line, #function, Double(imageData.count) / 1024 / 1024)
+                    break
+                }
+            }
+        } while (imageData.count > maxPayloadSizeInBytes)
```
Comment (DK1DA) [inline MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:140]: I'm wondering if there is any chance this can result in an infinite loop. Maybe have some limit e.g. ten iterations and then bail out?

**Review by kimar — APPROVED** [review]

File: MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift (hunk 3 above)
Comment (MainasuK) [reply MastodonSDK/Sources/MastodonUI/Scene/ComposeContent/Attachment/AttachmentViewModel+Compress.swift:140]: `let maxPayloadSizeInBytes = max((sizeLimit.image ?? 10 * 1024 * 1024), 1 * 1024 * 1024)`

Make sense. Now set the minimal payload limit size to 1MiB. So the loop should always finish even server configuration give a very small value like 1 byte. I'm sure limiting the count of the loop could be another workaround. However, it's lost the ability to control the file size.
