### PR TITLE
Bugfixes for "Load More" / Home Timeline Gap Loading (IOS-275)

### LINKED ISSUE #1288: [BUG] “Load missing posts” appears when there isn’t any
### Is there an existing issue for this?

- [X] I have searched the issues (both open and closed)

### Current Behavior

The “load missing posts” timeline item appears when there is no posts between the old and new timelines. So tapping it just makes it disappear and connect the two timeline sections 

### Expected Behavior

For the button to not be present when it’s not necessary 

### Steps To Reproduce

1. Open the app after a short time
2. Wait for the timeline to load and show “load missing posts”
3. Tap “load missing posts”
4. Observe no posts are loaded and the timelines are now connected

### Environment

```markdown
- Device: iPhone 12 Pro
- OS: iOS 17.4.1
- Version: v2024.5
- Build: 6336
```

### Anything else?

https://github.com/mastodon/mastodon-ios/assets/8526392/cb04673c-27f8-45de-9d52-b320df0a8d22

### PR DESCRIPTION
**Pull request by kimar**
Fixes #1288 and incorrectly ordered posts when loading more.

### CODE REVIEW

File: Mastodon/Scene/HomeTimeline/HomeTimelineViewModel.swift [hunk 1]
```diff
@@ -163,12 +163,11 @@ extension HomeTimelineViewModel {
         case .home:
             response = try? await context.apiService.homeTimeline(
                maxID: status.id,
-               limit: 20,
                authenticationBox: authContext.mastodonAuthenticationBox
            )
         case .public:
             response = try? await context.apiService.publicTimeline(
-                query: .init(maxID: status.id, limit: 20),
+                query: .init(maxID: status.id),
```
Comment (zeitschlag) [inline Mastodon/Scene/HomeTimeline/HomeTimelineViewModel.swift]: I guess you removed `limit` as the public timeline [defaults to 20 posts](https://docs.joinmastodon.org/methods/timelines/#public) nevertheless?

File: Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift [hunk 2]
```diff
@@ -119,7 +119,7 @@ extension HomeTimelineViewModel.LoadLatestState {
                 
                 /// To find out wether or not we need to show the "Load More" button
                 /// we have make sure to eventually overlap with the most recent cached item
-                let sinceID = latestFeedRecords.count > 1 ? latestFeedRecords[1].id : "1"
+                let sinceID = latestFeedRecords.count > 1 ? latestFeedRecords[1].id : nil
```
Comment (zeitschlag) [inline Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift:122]: Thank you!

File: Mastodon/Scene/HomeTimeline/HomeTimelineViewModel.swift (hunk 1 above)
Comment (zeitschlag) [inline Mastodon/Scene/HomeTimeline/HomeTimelineViewModel.swift]:
```suggestion
                query: .init(maxID: status.id),
                query: .init(local: true, maxID: status.id),
```

Just saw posts from other instances appearing in my local timeline 🫠

**Review by zeitschlag — COMMENTED** [review]
Most of the stuff looks good, it works most of the time, here it doesn't and I don't really get why:

D579C99E-0C9B-453D-A544-30D8F2CC7241_1_201_a

My guess is that there's a flaw when caclulating the `hasMore` in "load more", my culprit is the `if index < items.count - 1`-condition, but this is just a wild guess.

Maybe you could have another look at that?

**Review by zeitschlag — APPROVED** [review]
Still looks good from my perspective, I don't know how to fix the "Scroll to the bottom"-thing I sent you, but it's not a blocker for me, to be honest, as it only seems to appear, when you scroll to the bottom fast.
