### PR TITLE
Fixes #942 - Tapping home button or Pull to Refresh does not reload

### LINKED ISSUE #942: [BUG] Can't refresh
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I now have to kill the app (toss it away) and restart it to have the updated state of my instance reflected by the app.  

I think this behavior started w/ the v1.4.11 update

### Expected Behavior

Clicking the home button used to create a spinning disc until I got the purple "New Posts" button.  The home button now seems to have no effect, and I can't get the "New Posts" button by down-dragging the timeline, either.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Device: i6
- OS: iOS 15.7.3
- Version:v1.4.11
- Build:265
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kimar**
# Rationale

When introducing the haptic feedback, I made a distinction between manual and automated (event based) timeline reload. Unfortunately I partially broke the reload state machine there. This PR fixes this.

### CODE REVIEW

File: Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift [hunk 1]
```diff
@@ -51,7 +51,7 @@ extension HomeTimelineViewModel {
 extension HomeTimelineViewModel.LoadLatestState {
     class Initial: HomeTimelineViewModel.LoadLatestState {
         override func isValidNextState(_ stateClass: AnyClass) -> Bool {
-            return stateClass == Loading.self
+            return stateClass == Loading.self || stateClass == LoadingManually.self
```
Comment (zeitschlag) [inline Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift:54]: `HomeTimelineViewModel.LoadOldestState` is not affected, as there's no `LoadManually`-State (aka pull to refresh), right?

**Review by zeitschlag — APPROVED** [review]

File: Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift (hunk 1 above)
Comment (DK1DA) [reply Mastodon/Scene/HomeTimeline/HomeTimelineViewModel+LoadLatestState.swift:54]: Exactly!
